# Generated by Django 3.2.7 on 2021-10-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boBingModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField()),
                ('round', models.SmallIntegerField()),
                ('playerNum', models.SmallIntegerField()),
                ('nowLevel', models.SmallIntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boBingModel.player')),
            ],
        ),
    ]
