# Generated by Django 3.2.7 on 2021-10-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boBingModel', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='a.jpg', upload_to='photos'),
        ),
    ]
