# Generated by Django 3.2.7 on 2021-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boBingModel', '0005_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pid',
            field=models.IntegerField(),
        ),
    ]
